import type { Metadata } from "next";
import {Inter, Oswald, Manrope } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter",
});

const geIsOswald = Oswald({
  variable: "--font-oswald",
});

const geIsManrope = Manrope({
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${geIsOswald.variable} ${geIsManrope.variable} antialiased`}
      >
        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}
